### ISSUE TITLE
/tpack internal error

### ISSUE THREAD

**Issue by Karrade** [BlackPhantom3899/CranaZ#2]
trying to perform /tpack results in an internal error while using the following:
Spigot 1.8.3-R0.1 Snapshot
citizens-2.0.15-SNAPSHOT.jar
CrackShot v0.98.2

here is the error:
```
12.06 19:06:18 [Server] INFO ... 15 more
12.06 19:06:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at com.bp389.cranaz.CranaZ.onCommand(CranaZ.java:46) ~[?:?]
12.06 19:06:18 [Server] INFO at com.bp389.cranaz.Loader.parseCommand(Loader.java:91) ~[?:?]
12.06 19:06:18 [Server] INFO at com.bp389.cranaz.legacy.Legacy.onCommand(Legacy.java:68) ~[?:?]
12.06 19:06:18 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_40]
12.06 19:06:18 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_40]
12.06 19:06:18 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
12.06 19:06:18 [Server] INFO ... 15 more
12.06 19:06:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at com.bp389.cranaz.CranaZ.onCommand(CranaZ.java:46) ~[?:?]
12.06 19:06:18 [Server] INFO at com.bp389.cranaz.Loader.parseCommand(Loader.java:91) ~[?:?]
12.06 19:06:18 [Server] INFO at com.bp389.cranaz.legacy.Legacy.onCommand(Legacy.java:68) ~[?:?]
12.06 19:06:18 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
12.06 19:06:18 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
12.06 19:06:18 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:712) [spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
12.06 19:06:18 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
12.06 19:06:18 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at net.minecraft.server.v1_8_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:974) [spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at net.minecraft.server.v1_8_R2.PlayerConnection.handleCommand(PlayerConnection.java:1139) [spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-BT36_1.8.3_05.15.jar:git-Spigot-870264a-0a645a2]
12.06 19:06:18 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'tpack' in plugin CranaZ v2.437b
12.06 19:06:18 [Server] INFO [19:06:18 ERROR]: null
```

I dont know how to get the full stacktrace, i also dont know why its in reversed order on my server lol sorry about that

Downgrading to spigot 1.8 solves the issue for me, but creates an issue with citizens2 plugin

**Comment by BlackPhantom3899** [comment]
Citizens 2.0.15 seems to be broken, as this version is no more available to download. I think the error is caused because you can also name a NPC "torteela", who will open the resource pack GUI when right clicked. All functions linked to Citizens will soon be removed, keeping CrackShot as only depedency.
